export const componentsCopy = {
  app: {
    skipToContent: 'К содержимому',
    closeMenu: 'Закрыть меню',
    sections: 'Разделы',
    appSections: 'Разделы приложения',
    menu: 'Меню',
    install: 'Установить',
    buildLabel: (version: string) => `Сборка ${version}`,
  },
  identity: {
    hint: 'Грубый онбординг M1: ключ локально, без облака. Биометрия — удобный unlock, не единственное восстановление.',
    passphrase: 'Мастер-фраза',
    seedLabel: 'Seed BIP39 (12 слов)',
    backupLabel: 'Содержимое nb1. бэкапа',
    saveSeed: 'Сохраните seed-фразу (один раз):',
    fingerprint: 'Fingerprint:',
    enter: 'Войти',
    continue: 'Продолжить',
    copyBackup: 'Копировать бэкап',
    createNew: 'Создать новую',
    unlock: 'Разблокировать',
    fromSeed: 'Из seed',
    fromBackup: 'Из бэкапа',
    unlockBio: 'Войти с биометрией',
    enableBio: 'Включить биометрию',
    bioEnabled: 'Биометрия включена на этом устройстве.',
    bioUnavailable: 'Биометрия недоступна — войдите мастер-фразой.',
    bioFallback: 'Биометрия не сработала — введите мастер-фразу.',
  },
  calls: {
    hint: 'Голос, видео или экран — по тому же каналу, что и файлы. Нужны S1 и контакт в сети.',
    bookEmpty: 'Нет контактов. Добавьте в разделе «Контакты».',
    online: 'в сети',
    offline: 'не в сети',
    inCall: 'в звонке',
    audio: 'Аудио',
    video: 'Видео',
    screen: 'Экран',
    hangUp: 'Завершить',
    dismiss: 'Понятно',
    accept: 'Принять',
    reject: 'Отклонить',
    localLabel: 'Вы',
    remoteLabel: 'Собеседник',
    calling: 'Звоним…',
    ringing: 'Входящий звонок…',
    active: 'Звонок идёт',
    needPermission: 'Нужен доступ к микрофону или камере.',
  },
  transfer: {
    filesLegend: 'Файлы',
    pickFileAria: 'Выбрать файлы для отправки',
    pickFolderAria: 'Выбрать папку для отправки',
    pickFiles: 'Файлы',
    pickFolder: 'Папка',
    clear: 'Очистить',
    filesEmpty: 'Пока ничего не выбрано',
    folderFiles: (count: number) => `${count} файлов`,
    toLegend: 'Кому',
    bookEmpty: 'Нет контактов. Добавьте в разделе «Контакты».',
    online: 'в сети',
    offline: 'не в сети',
    inCall: 'канал открыт',
    send: 'Передать',
    knock: 'Постучать',
    acceptFolder: 'Принять папку',
    acceptFile: 'Принять файл',
    reject: 'Отклонить',
    cancel: 'Отменить',
    progressLegend: 'Прогресс',
  },
  servers: {
    savedLegend: 'Сохранённые серверы',
    savedEmpty:
      'Пока пусто. Сохраните пакет S1. выше или ручную конфигурацию ниже.',
    active: 'выбран',
    select: 'Выбрать',
    details: 'Подробности',
    probe: 'Проверить',
    remove: 'Удалить',
    manualLegend: 'Ручная конфигурация',
    manualHint:
      'Заполните сокет и ICE, проверьте доступность и сохраните — сервер появится в списке выше.',
    socketUrl: 'Адрес сокета',
    stun: 'STUN, по одному URL в строке',
    turn: 'TURN, по одному URL в строке',
    turnUser: 'TURN логин',
    turnPass: 'TURN пароль',
    iceJson: 'или iceServers JSON',
    saveToList: 'Сохранить в список',
    relayLegend: 'Пучок реле (M1)',
    relayHint:
      'Несколько URL сигналинга, активен один. Переключение вручную — без авто-failover.',
    relayUrl: 'URL реле',
    relayAdd: 'Добавить',
    relaySelect: 'Сделать активным',
    relayRemove: 'Убрать',
    relayEmpty: 'Пока пусто — добавьте wss:// или https:// адрес реле.',
    relayActive: 'активно',
  },
  pendingPeer: {
    legend: 'Новый человек',
    accept: 'В адресную книгу',
    skip: 'Не сейчас',
  },
  logs: {
    legend: 'Логи',
    hint: 'Сессия, ICE и ошибки. Файл app.log лежит в OPFS этого устройства.',
    ariaLabel: 'Журнал приложения',
    empty: 'Пока пусто',
    clear: 'Очистить',
  },
  invite: {
    legend: 'Приглашение',
    channelOpen: 'Канал открыт',
    roomAutoOpen: 'Оба в одной комнате — канал откроется сам',
    callerHint: 'Отправьте текст второму окну, затем вставьте его ответ',
    calleeHint:
      'Вставьте приглашение или пакет S1. с серверов, затем отдайте ответ',
    shareServers:
      'Вложить мои серверы: если у второго нет TURN/сокета — пусть возьмёт эти',
    qrAlt: 'QR приглашения',
    outgoingAria: 'Исходящее приглашение',
    copy: 'Скопировать',
    shareLink: 'Поделиться ссылкой',
    pastePlaceholder: 'Вставьте приглашение или ответ',
    incomingAria: 'Входящее приглашение или ответ',
    acceptText: 'Принять текст',
  },
  inbox: {
    legend: 'Получено на этом телефоне',
    save: 'Сохранить',
    remove: 'Удалить',
    listAria: 'Полученные файлы',
    opfsUnavailable: 'OPFS недоступен в этом браузере',
    empty: 'Пока пусто',
    saved: 'Сохранено на устройство.',
    saveAborted: 'Сохранение отменено.',
    saveFailed: 'Не удалось сохранить файл.',
  },
  host: {
    installLegend: 'Установить на VPS',
    installHint:
      'Зайдите по SSH на сервер и выполните одну строку. Скрипт спросит пароль TURN, порты и поднимет сокет с HTTPS. В конце консоль напечатает пакет S1. и QR.',
    installAria: 'Команда установщика',
    copy: 'Копировать',
    packLegend: 'Сохранить пакет',
    packHint:
      'Вставьте S1. из консоли VPS — сервер появится в списке и станет активным.',
    packLabel: 'Пакет S1.',
    savePack: 'Сохранить пакет',
    scanQr: 'Считать QR',
  },
  home: {
    legend: 'Как связаться',
    openContacts: 'Открыть контакты',
    stepPickFile: 'Выберите файл в блоке «Файлы».',
    stepGetLink: 'Нажмите «Получить ссылку».',
    stepSendLink: 'Отправьте ссылку второму. Он открывает и принимает.',
    shareUrlReady: 'Эту ссылку отправьте второму — он только откроет',
    shareUrlPending: 'Ссылка появится здесь после «Получить ссылку»',
    shareUrlAria: 'Ссылка для второго устройства',
    copyLink: 'Копировать ссылку',
    pasteLabel:
      'Пришло от другого — вставьте ссылку, если по клику не открылось',
    pastePlaceholder: 'https://…/#r/… или текст приглашения',
    pasteAria: 'Вставить чужую ссылку или приглашение',
    acceptLink: 'Принять ссылку',
    copyId: 'Копировать id',
    recipientLegend: 'Кому',
    bookEmpty:
      'Книга пуста. Ссылка всё равно сработает — карточка придёт при связи.',
    groupLabel: (name: string, count: number) => `группа «${name}» · ${count}`,
    createInvite: 'Создать приглашение',
    openedForeignInvite: 'Я открыл чужое приглашение',
  },
  help: {
    legend: 'Справка',
    hint: 'Коротко о приложении и установке.',
  },
  contacts: {
    needS1Before: 'Сначала вставьте пакет S1. в',
    needS1Link: '«Настройки сервера»',
    needS1After:
      'на обоих устройствах (телефон и комп). Одна Wi‑Fi без S1 канал не откроет.',
    meLegend: 'Я',
    nick: 'Ник',
    nickAria: 'Ник',
    cardReady: 'Поделиться карточкой',
    cardAria: 'Ваша карточка контакта',
    saveNick: 'Сохранить ник',
    pickPhoto: 'Своё фото',
    edit: 'Редактировать',
    copy: 'Копировать карточку',
    qrAlt: 'QR карточки «это я»',
    goAvailable: 'Я в сети',
    goUnavailable: 'Офлайн',
    availableHint:
      'Пока приложение открыто — вы в сети сами. Кнопка вверху: временно офлайн. Контакты видят зелёную точку и могут постучаться.',
    presenceOnLabel: 'Вы в сети — нажмите, чтобы временно выйти',
    presenceOffLabel:
      'Сейчас офлайн. Нажмите или снова откройте приложение — будете в сети',
    knock: 'Постучать',
    addLegend: 'Добавить контакт',
    addHint:
      'Вставьте чужую карточку P1. или представление I1. Нужен S1. Пока приложение открыто — вы в сети. «Представить» копирует I1. для третьего.',
    cardField: 'Карточка',
    cardFieldAria: 'Карточка контакта или представление I1.',
    add: 'Добавить',
    introduce: 'Представить',
    listLegend: 'Контакты',
    listEmpty:
      'Пока пусто. Вставьте чужую карточку выше — сразу появится здесь.',
    online: 'в сети',
    offline: 'не в сети',
    inCall: 'канал открыт',
    remove: 'Удалить',
    rename: 'Переименовать',
    saveAlias: 'Сохранить имя',
    aliasLabel: 'Имя у вас',
    aliasAria: 'Локальное имя контакта',
    networkNick: (nick: string) => `в сети: ${nick}`,
    groupLegend: 'Группа',
    groupHint: 'Локальный ярлык. Канал всё равно 1:1.',
    groupName: 'Название',
    saveGroup: 'Сохранить группу',
    groupMembers: (count: number) => `${count} чел.`,
  },
} as const;
