export const filePipeCopy = {
  rejected: 'отклонено',
  busy: 'занято',
  fileTooLargeOrBadName: 'файл слишком большой или имя недопустимо',
  folderEmptyOrBadName: 'папка пуста или имя недопустимо',
  tooManyFiles: 'слишком много файлов',
  fileTooLargeOrBadPath: 'файл слишком большой или путь недопустим',
  noOpfs: 'нет OPFS',
  noSpace: 'нет места',
  transferInProgress: 'Уже идёт передача',
  invalidPath: 'Недопустимый путь',
  fileOverLimit: 'Файл больше лимита',
  invalidFileName: 'Недопустимое имя файла',
  folderEmpty: 'Папка пуста',
  tooManyFolderFiles: 'Слишком много файлов в папке',
  invalidFolderPath: 'Недопустимый путь в папке',
  folderFileOverLimit: 'Файл в папке больше лимита',
  invalidFolderWalkPath: 'Недопустимый путь в папке',
  invalidFolderName: 'Недопустимое имя папки',
} as const;
