export const shellCopy = {
  checking: 'Проверяем…',
  reloading: 'Есть новая сборка, перезагрузка…',
  confirmCurrent:
    'Сборка уже эта. Сбросить кэш PWA и перезагрузить? На iPhone так подхватывается релиз без удаления.',
  confirmFailed: 'Не удалось проверить версию. Сбросить кэш и перезагрузить?',
  wipingCache: 'Сбрасываем кэш…',
  upToDate: 'Сборка актуальная',
  checkFailed: 'Проверка не удалась',
  checkUpdate: 'Проверить обновление',
  listTitle: 'Разделы',
  listAria: 'Список контактов и разделов',
  contactsTitle: 'Контакты',
  contactsEmpty: 'Пока пусто — добавьте карточку в разделе «Контакты».',
  backToList: 'К списку',
  stubChatsTitle: 'Чаты',
  stubChatsHint: 'Здесь будут диалоги. Пока открывайте контакты выше.',
  stubEmptyTitle: 'Пустой чат',
  stubEmptyText:
    'Заглушка M1: полноценный чат появится позже. Сейчас — контакты, звонки и файлы.',
  sectionHint: 'Раздел',
  openCalls: 'Звонок',
  openContacts: 'Карточка',
  knock: 'Постучаться',
} as const;
