export const shellCopy = {
  checking: 'Проверяем…',
  reloading: 'Есть новая сборка, перезагрузка…',
  confirmCurrent:
    'Сборка уже эта. Сбросить кэш PWA и перезагрузить? На iPhone так подхватывается релиз без удаления.',
  confirmFailed: 'Не удалось проверить версию. Сбросить кэш и перезагрузить?',
  wipingCache: 'Сбрасываем кэш…',
  upToDate: 'Сборка актуальная',
  checkFailed: 'Проверка не удалась',
  checkUpdate: 'Проверить обновление',
  listTitle: 'Разделы',
  listAria: 'Список чатов',
  tabsAria: 'Основные разделы',
  tabProfile: 'Профиль',
  tabCalls: 'Звонки',
  tabChats: 'Чаты',
  tabSettings: 'Настройки',
  drawerTitle: 'Настройки',
  drawerLogs: 'Логи',
  drawerHelp: 'Справка',
  drawerServers: 'Настройки сервера',
  drawerPersonal: 'Личные настройки',
  contactsTitle: 'Чаты',
  contactsEmpty:
    'Пока пусто — добавьте контакт во вкладке «Профиль», затем откройте чат здесь.',
  selfChatTitle: 'Записная книжка',
  selfChatDetail: 'Только на этом устройстве',
  selfChatHint: 'Заметки себе — никуда не отправляются, только локально.',
  callsTitle: 'Звонки',
  callsEmpty: 'Пока нет входящих и исходящих. Начните звонок из чата.',
  callOutgoing: 'Исходящий',
  callIncoming: 'Входящий',
  callMissed: 'Пропущенный',
  callEnded: 'Завершён',
  callFailed: 'Не удался',
  callRejected: 'Отклонён',
  backToList: 'К чатам',
  backToCalls: 'К звонкам',
  sectionHint: 'Раздел',
  openCalls: 'Звонок',
  openContacts: 'Карточка',
  knock: 'Постучаться',
  introduce: 'Представить',
  transferTitle: 'Файлы',
  transferHint:
    'Тот же transfer, что в «Передача» — прямо из сессии с контактом.',
  transferIdle: 'Выберите файлы и отправьте этому контакту.',
  transferStaged: (count: number) =>
    count === 1 ? 'В очереди 1 файл' : `В очереди ${count} файлов`,
  transferSend: 'Отправить',
  transferMore: 'Полная передача',
  chatEmptyTitle: 'Нет сообщений',
  chatEmptyHint: 'Напишите первое сообщение — так вы запросите переписку.',
  chatComposerLabel: 'Сообщение',
  chatComposerPlaceholder: 'Сообщение',
  chatSend: 'Отправить',
  chatLocalOnly:
    'Сообщения уходят по DataChannel, когда канал с контактом открыт; иначе остаются локально.',
  chatNeedIdentity: 'Сначала разблокируйте личность.',
  chatQueuedLocal:
    'Сохранено здесь. Стучимся к контакту — когда канал откроется, отправьте ещё раз или постучите вручную.',
  personalTitle: 'Личные настройки',
  personalHint: 'Идентичность, тема (в шапке) и передача файлов.',
  personalId: 'Ваш ID',
  personalTransfer: 'Передача файлов',
  personalLock: 'Выйти из учётки',
  personalLockHint:
    'Ключ остаётся в vault на устройстве; нужна мастер-фраза или биометрия.',
} as const;
